name: Create AKS cluster

on:
  push:
    paths:
      - "**/az-*.yml"

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Create AKS cluster -1
      uses: 'docker://sixeyed/actions-aks-create-cluster:1910'
      env:
        AZURE_SP_NAME: ${{ secrets.AZURE_SP_NAME }}
        AZURE_SP_TENANT: ${{ secrets.AZURE_SP_TENANT }}
        AZURE_SP_PASSWORD: ${{ secrets.AZURE_SP_PASSWORD }}
        AZURE_SP_APP_ID: ${{ secrets.AZURE_SP_APP_ID }}
        AZURE_RESOURCE_GROUP: eshopweb5
        AZURE_REGION: eastus
        AKS_CLUSTER_NAME: eshopweb5-aks
        AKS_NODE_COUNT: 2
